### ISSUE TITLE
Compatible with IE10 or even IE9?

### ISSUE THREAD

**Issue by geri777** [matthias-schuetz/angular2-seed#12]
Is it possible to use the seed project if I want to run the app on IE10 or even IE9? Is there any easy solution like shim, or transpile to ES5 ?

**Comment by matthias-schuetz** [comment]
I'm sorry to say that I'm currently not aware of an easy solution to support IE9/IE10 or transpile to ES5. The seed only makes use of the frameworks but browser support is subject to Angular/Rxjs/etc.
