### ISSUE TITLE
Question about shared dir

### ISSUE THREAD

**Issue by jessethach** [matthias-schuetz/angular2-seed#7]
Is there any reason that the shared folder path has a `+`?

`C:\Users\user\Source\Repos\project\app\src\components\+shared\`

This was causing some errors when deploying on a Windows 2012 Server. Just wanted to give you a heads up!

**Comment by matthias-schuetz** [comment]
The `+` was only for distinguish reasons so that `shared` is always the first item in file managers. But I changed it to `_shared` so the problems on Windows 2012 Server should be gone. Thanks for the information!
